name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: 20.12.2 # Puedes ajustar la versión de Node.js según la compatibilidad de tu proyecto
          package-manager: pnpm@9.7.0 # Especifica aquí la versión de pnpm que desees usar

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2' # Asegúrate de usar una versión de Node compatible
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build and Deploy
        run: pnpm run build && pnpm run deploy
        env:
          CI: true
